language: swift
osx_image: xcode11

branches:
  only:
    - master
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
  - rvm install ruby-2.4.2
install:
  - bundle install --without=documentation
script:
  - set -o pipefail
  - swift package generate-xcodeproj --enable-code-coverage
  - xcodebuild -project Muck.xcodeproj -scheme Muck-Package -derivedDataPath "$PWD/.xcbuild" clean build test | bundle exec xcpretty
after_success:
  - bundle exec slather
